version: '2'

services:

    db:
        image: mysql
        ports:
            - "13306:3306"
        volumes:
          - ./var/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: root
            MYSQL_PASSWORD: root

    php:
        build: ./docker/php-fpm
        expose:
            - 9000
        volumes:
          - ./:/var/www
        links:
            - db

    nginx:
        build: ./docker/nginx
        ports:
            - 80:80
        expose:
            - 80
        links:
            - php
        volumes_from:
            - php