version: '2'

services:

  # SSH Agent container
  ssh_agent:
    build: docker/ssh_agent

  # SSH Add Keys container
  ssh_add_key:
    build: docker/ssh_agent
    volumes:
      - ~/.ssh:/ssh
    volumes_from:
      - ssh_agent

  # SSH Daemon container for Xdebug tunnel
  sshd:
    build:
      context: docker/sshd
      dockerfile: Dockerfile

  # PHP-FPM Container
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    volumes_from:
      - ssh_agent
    environment:
      SSH_AUTH_SOCK: /root/.ssh/socket

  # Nginx HTTP dameon container
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes_from:
      - php
    environment:
      NGINX_HOST: boilerplate.loc
      PHP_INDEX: app_dev.php
    links:
      - php

  # Redis container
  redis:
    build:
      context: docker/redis
      dockerfile: Dockerfile
    volumes:
      - ./var/redis:/data
